v0.3.1

diff --git a/vessl b/vessl
--- a/vessl
+++ b/vessl
@@ -3,7 +3,7 @@
 ######################
 ################
 #
-# vessl - 0.2
+# vessl - 0.3.1
 #
 #	Usage: vessl -h host [-p port] [-c certfile] [-v]	
 #
@@ -11,7 +11,7 @@
 #
 #		Copyright (C) 21/08/2008 - deanx <RID[at]portcullis-secuirty.com>
 #	
-#	Version 0.2 
+#	Version 0.3.1 
 #	
 #	* This program is free software; you can redistribute it and/or modify
 #	* it under the terms of the GNU General Public License as published by
@@ -34,8 +34,8 @@
 port="443"
 host="NOTSET"
 cafile="/etc/certs/mozilla.pem"
-verify=`mktemp -t vessl`
-cert=`mktemp -t vessl`
+verify=`mktemp -t vesslXXXXXX`
+cert=`mktemp -t vesslXXXXXX`
 
 while getopts "h:p:?c:v" o
 	do
@@ -61,17 +61,50 @@ if [ ! -r $cafile ]
 	exit 1
 fi
 
+a=`which ping | grep no | cut -f 1 -d " "`
+
+if [ ! -w "." ];
+	then echo -en "\n\t[!] CWD is not writeable please sort this out as no files will be written, dumping to screen\n"
+	verbose=1
+	copy=1
+fi
+
+if [ ! -x $a ];
+	then echo -en "\n\t[!] ping is not in your path!\n"
+	exit 1
+fi
+
+
+a=`which openssl | grep no | cut -f 1 -d " "`
+
+if [ ! -x $a ];
+	then echo -en "\n\t[!] openssl is not in your path!\n"
+	exit 1
+fi
+
+a=`which openssl-vulnkey | grep no | cut -f 1 -d " "`
+
+if [ ! -x $a ];
+	then echo -en "\n\t[!] openssl-vulnkey is not in your path, disabling debian weak key detection!\n"
+	echo -en "\t\t check out https://launchpad.net/ubuntu/+source/openssl-blacklist/\n"
+	debian=1
+fi
+
+
 ip=`ping -c 1 -t 1 -i 1 $host 2>/dev/null| grep data | cut -d\( -f 2| cut -f 1 -d\)`
 
 if [ ! $verbose ];
-	then echo -en "\n\t[+] Connecting to $host:$port which resolves as $ip\n\n"
+	then echo -en "\n\t[+] Connecting to $host:$port which resolves as $ip\n"
 fi
 
 echo "Connecting to $host:$port which resolves as $ip" >> $verify
 echo | openssl s_client -showcerts -verify 9 -CAfile $cafile -connect $host:$port 2>>$verify | openssl x509 -text 2>/dev/null > $cert
 
 if [ $? -ne  0 ]; then
-	echo -en "\t[!] Connection/Certificate Retrieval Failed\n\n";
+	if [ $verbose ];
+			then echo -en "\n\t[+] Connecting to $host:$port which resolves as $ip\n"
+	fi
+	echo -en "\n\t[!] Connection/Certificate Retrieval Failed\n\n";
 	rm $verify
 	rm $cert
 	exit 1
@@ -91,13 +124,32 @@ else
 fi
 
 echo "$ip:$port, $rhost ($rip)" >> $verify
-echo "$ip:$port, $rhost ($rip)" >> sslmap
+
+
+
+if [ ! $debian ];
+	then openssl-vulnkey $cert >> $verify
+	if [ $? -ne 0 ]
+		then echo "verify error:num=98:debian weak key detected" >> $verify
+	fi
+	
+fi
 
 if [ $verbose ]; then
+	echo
 	cat $verify
 fi
 
-cp $verify $ip\:$port.verify
-cp $cert $ip\:$port.cert
+if [ ! $copy ]; then
+	if [ ! $verbose ]; then 
+		echo -en "\n\t[+] Map data added to ./sslmap\n"
+		echo -en "\n\t[+] Verification data written to ./$ip:$port.verify\n"
+		echo -en "\n\t[+] Certificate written to ./$ip:$port.cert\n"
+	fi
+	echo "$ip:$port, $rhost ($rip)" >> sslmap
+	cp $verify $ip\:$port.verify
+	cp $cert $ip\:$port.cert
+fi
+echo
 rm $verify
 rm $cert
